<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('plan_items', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->cascadeOnDelete();
            $table->foreignId('learning_item_id')->constrained()->cascadeOnDelete();
            $table->foreignId('activity_id')->constrained()->cascadeOnDelete();

            $table->date('scheduled_for');
            $table->unsignedSmallInteger('duration_minutes');

            $table->enum('status', ['scheduled', 'completed', 'skipped', 'rescheduled', 'expired'])->default('scheduled');

            // 'plan' = generated by the weekly/daily planner, 'review' = due spaced review,
            // 'recovery' = generated by the recovery planner after missed days.
            $table->enum('source', ['plan', 'review', 'recovery'])->default('plan');

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('plan_items');
    }
};
